---
uninstall_homebrew_steps:
  - curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall
  - chmod +x ./uninstall
  - ./uninstall --force
  - rm -rf /usr/local/Homebrew
  - rm -rf /usr/local/Caskroom
  - rm -rf /usr/local/bin/brew

homebrew_installed_packages:
  - chromedriver
  - redis
  - elasticsearch@2.4
  - rbenv
  - phantomjs
  - ssh-copy-id
  - git
  - wget

homebrew_cask_apps: []
  # - atom
  # - google-chrome

clt_path: /Library/Developer/CommandLineTools

chapman_apps:
  - cascade-assets
  - signage
  - blogs
  - inside