---
- name: Setup Chapman github repositories
  git: 
    #repo: "http://{{ githubuser }}:{{ githubpass }}@github.com/chapmanu/{{ item }}" 
    repo: "http://github.com/chapmanu/{{ item }}"
    dest: "~/{{ item }}"
    accept_hostkey: yes
  with_items: "{{ chapman_apps }}"